TOP_PICKS_BUCKETS = [
    {
        "title": "Better work setup",
        "subtitle": "Make calls, writing, and focus time smoother.",
        "items": [
            {
                "slug": "mini-mic-pro",
                "name": "Mini Mic Pro (latest model)",
                "description": "Clip-on wireless mic for crisp audio on Zoom calls and video.",
                "price": "$24.99",
                "reviews": "5,800+ reviews",
                "url": "https://amzn.to/4sgpN8o",
                "image": "/static/top_picks/mini-mic-pro.jpg",
            },
            {
                "slug": "apple-earpods-usbc",
                "name": "Apple EarPods with USB-C",
                "description": "Simple wired earbuds with remote for meetings and music.",
                "price": "$17.99",
                "reviews": "22k+ reviews",
                "url": "https://amzn.to/49uC8OQ",
                "image": "/static/top_picks/apple-earpods-usbc.jpg",
            },
            {
                "slug": "airpods-pro-3",
                "name": "AirPods Pro 3",
                "description": "Noise cancelling wireless earbuds with spatial audio.",
                "price": "$229.99",
                "reviews": "3,200+ reviews",
                "url": "https://amzn.to/49awTml",
                "image": "/static/top_picks/airpods-pro-3.jpg",
            },
            {
                "slug": "leather-desk-pad",
                "name": "Leather desk pad",
                "description": "Large non-slip desk mat that turns any table into a clean workspace.",
                "price": "$6.96",
                "reviews": "74k+ reviews",
                "url": "https://amzn.to/4jg79JS",
                "image": "/static/top_picks/leather-desk-pad.jpg",
            },
        ],
    },
    {
        "title": "Habit and home helpers",
        "subtitle": "Tiny upgrades that remove daily friction.",
        "items": [
            {
                "slug": "mighty-patch",
                "name": "Mighty Patch Original",
                "description": "Overnight pimple patches to shrink whiteheads while you sleep.",
                "price": "$12.99",
                "reviews": "179k+ reviews",
                "url": "https://amzn.to/499ueJw",
                "image": "/static/top_picks/mighty-patch.jpg",
            },
            {
                "slug": "zevo-refills",
                "name": "Zevo trap refills",
                "description": "Refill cartridges for Zevo traps to catch gnats and house flies 24/7.",
                "price": "$14.97",
                "reviews": "33k+ reviews",
                "url": "https://amzn.to/4at2Qsi",
                "image": "/static/top_picks/zevo-refills.jpg",
            },
            {
                "slug": "muddy-mat",
                "name": "Muddy Mat door mat",
                "description": "Super absorbent entry mat that traps mud and water from paws and shoes.",
                "price": "$24.95",
                "reviews": "39k+ reviews",
                "url": "https://amzn.to/4p9igW7",
                "image": "/static/top_picks/muddy-mat.jpg",
            },
            {
                "slug": "door-balancer",
                "name": "Door Balancer hook",
                "description": "Simple metal hook that keeps interior doors from drifting shut.",
                "price": "$7.99",
                "reviews": "1,000+ reviews",
                "url": "https://amzn.to/49712CU",
                "image": "/static/top_picks/door-balancer.jpg",
            },
        ],
    },
    {
        "title": "Travel and find-your-stuff",
        "subtitle": "Keep track of keys, bags, and everything that likes to wander.",
        "items": [
            {
                "slug": "apple-airtag",
                "name": "Apple AirTag",
                "description": "Tiny tracker that helps you find keys, bags, and more with your iPhone.",
                "price": "$19.00",
                "reviews": "48k+ reviews",
                "url": "https://amzn.to/4b9h3eb",
                "image": "/static/top_picks/apple-airtag.jpg",
            },
        ],
    },
    {
        "title": "Fun dopamine toy",
        "subtitle": "A little treat for your desk or coffee table.",
        "items": [
            {
                "slug": "tosy-magnet-pyramid",
                "name": "TOSY Magnet Pyramid cube",
                "description": "Magnetic shape-shifting puzzle cube with endless fidget patterns.",
                "price": "$29.99",
                "reviews": "3,400+ reviews",
                "url": "https://amzn.to/49gIFvu",
                "image": "/static/top_picks/tosy-magnet-pyramid.jpg",
            },
        ],
    },
]
