from __future__ import annotations

from typing import Any, Dict, List, Optional

ToolInput = Dict[str, Any]
ToolEntry = Dict[str, Any]


def get_tools_registry() -> List[ToolEntry]:
    """Return the current list of registered tools."""
    return [
        {
            "slug": "resume-bullets",
            "title": "Resume Bullet Improver",
            "description": "Turn rough experience notes into strong, measurable resume bullets.",
            "category": "Career",
            "is_enabled": True,
            "output_label": "Improved bullets",
            "inputs": [
                {
                    "name": "experience_text",
                    "label": "Experience notes",
                    "type": "textarea",
                    "required": True,
                    "max_chars": 3000,
                    "placeholder": "Paste raw experience notes, tasks, or accomplishments to improve.",
                },
                {
                    "name": "target_role",
                    "label": "Target role",
                    "type": "text",
                    "required": False,
                    "max_chars": 120,
                    "placeholder": "e.g., IT Support Specialist",
                },
                {
                    "name": "job_description",
                    "label": "Job description (optional)",
                    "type": "textarea",
                    "required": False,
                    "max_chars": 3000,
                    "placeholder": "Paste the job post text to align keywords (optional).",
                },
                {
                    "name": "tone",
                    "label": "Tone",
                    "type": "select",
                    "required": False,
                    "max_chars": 50,
                    "placeholder": "",
                    "options": ["Direct", "Professional", "Technical"],
                    "default": "Professional",
                },
            ],
        },
        {
            "slug": "daily-checkin",
            "title": "Daily Habit Check-In",
            "description": "Track one habit per day with a simple done or skipped check-in.",
            "category": "Habits",
            "is_enabled": True,
            "output_label": "Status",
            "inputs": [
                {
                    "name": "habit_name",
                    "label": "Habit name",
                    "type": "text",
                    "required": True,
                    "max_chars": 80,
                    "placeholder": "e.g., Walk 20 minutes",
                },
                {
                    "name": "status",
                    "label": "Status",
                    "type": "select",
                    "required": True,
                    "max_chars": 10,
                    "placeholder": "",
                    "options": ["Done", "Skipped"],
                    "default": "Done",
                },
            ],
        },
        {
            "slug": "expense-splitter",
            "title": "Expense Splitter",
            "description": "Create a simple shared expense sheet and see who owes who.",
            "category": "Finance",
            "is_enabled": False,
            "output_label": "Settlement",
            "inputs": [
                {
                    "name": "event_name",
                    "label": "Event name",
                    "type": "text",
                    "required": True,
                    "max_chars": 80,
                    "placeholder": "e.g., Tahoe trip",
                },
                {
                    "name": "participants",
                    "label": "Participants",
                    "type": "text",
                    "required": True,
                    "max_chars": 400,
                    "placeholder": "e.g., Will, Sam, Jordan",
                },
                {
                    "name": "expenses",
                    "label": "Expenses",
                    "type": "textarea",
                    "required": True,
                    "max_chars": 5000,
                    "placeholder": "Format: payer | amount | description | split(optional)\nExamples:\nWill | 60 | Groceries\nSam | 120 | Airbnb | Will, Sam, Jordan\nJordan | 30 | Gas | Sam, Jordan",
                },
            ],
        },
        {
            "slug": "trip-planner",
            "title": "Trip Planner",
            "description": "Plan a trip, track budgets, and settle shared expenses with a shareable link.",
            "category": "Travel",
            "is_enabled": True,
            "output_label": "Trip summary",
            "inputs": [
                {
                    "name": "trip_name",
                    "label": "Trip name",
                    "type": "text",
                    "required": True,
                    "max_chars": 80,
                    "placeholder": "e.g., Tahoe trip",
                },
                {
                    "name": "currency",
                    "label": "Currency",
                    "type": "select",
                    "required": True,
                    "max_chars": 3,
                    "placeholder": "",
                    "options": ["USD", "EUR", "GBP"],
                    "default": "USD",
                },
                {
                    "name": "notes",
                    "label": "Notes",
                    "type": "textarea",
                    "required": False,
                    "max_chars": 1000,
                    "placeholder": "Key details, packing notes, or reminders.",
                },
            ],
        },
        {
            "slug": "daily-phrase",
            "title": "Daily Language Phrase",
            "description": "Learn one useful phrase per day, no streaks, no pressure.",
            "category": "Language",
            "is_enabled": True,
            "output_label": "Today's phrase",
            "inputs": [
                {
                    "name": "language",
                    "label": "Language",
                    "type": "select",
                    "required": True,
                    "max_chars": 20,
                    "placeholder": "",
                    "options": ["Spanish", "French", "German", "Italian", "Japanese"],
                    "default": "Spanish",
                },
                {
                    "name": "level",
                    "label": "Level",
                    "type": "select",
                    "required": True,
                    "max_chars": 20,
                    "placeholder": "",
                    "options": ["Beginner", "Intermediate", "Advanced"],
                    "default": "Beginner",
                },
            ],
        },
        {
            "slug": "decision-helper",
            "title": "Personal Decision Helper",
            "description": "Compare options and get a clear recommendation.",
            "category": "Productivity",
            "is_enabled": True,
            "output_label": "Recommendation",
            "inputs": [
                {
                    "name": "decision",
                    "label": "What decision are you making?",
                    "type": "text",
                    "required": True,
                    "max_chars": 120,
                    "placeholder": "Where should I move?",
                },
                {
                    "name": "options",
                    "label": "Options with pros/cons",
                    "type": "textarea",
                    "required": True,
                    "max_chars": 3000,
                    "placeholder": "Option A | pros | cons\nOption B, pros: ..., cons: ...",
                },
                {
                    "name": "priority",
                    "label": "Priority",
                    "type": "select",
                    "required": False,
                    "max_chars": 30,
                    "placeholder": "",
                    "options": ["Balanced", "Lowest risk", "Highest upside", "Lowest cost", "Fastest", "Most fun"],
                    "default": "Balanced",
                },
                {
                    "name": "constraints",
                    "label": "Constraints (optional)",
                    "type": "textarea",
                    "required": False,
                    "max_chars": 1000,
                    "placeholder": "Budget 500, must be done by Friday, no travel",
                },
            ],
        },
        {
            "slug": "worth-it",
            "title": "Is This Worth It? Calculator",
            "description": "Turn cost and time into cost-per-hour clarity plus a quick recommendation.",
            "category": "Productivity",
            "is_enabled": True,
            "output_label": "Recommendation",
            "inputs": [
                {
                    "name": "item_name",
                    "label": "Item or decision",
                    "type": "text",
                    "required": True,
                    "max_chars": 80,
                    "placeholder": "Gym membership",
                },
                {
                    "name": "mode",
                    "label": "Mode",
                    "type": "select",
                    "required": True,
                    "max_chars": 20,
                    "placeholder": "",
                    "options": ["enjoyment", "time_saved"],
                    "default": "enjoyment",
                },
                {
                    "name": "cost",
                    "label": "Cost",
                    "type": "text",
                    "required": True,
                    "max_chars": 30,
                    "placeholder": "360",
                },
                {
                    "name": "frequency",
                    "label": "Frequency",
                    "type": "select",
                    "required": True,
                    "max_chars": 20,
                    "placeholder": "",
                    "options": ["One-time", "Daily", "Weekly", "Biweekly", "Monthly", "Yearly"],
                    "default": "One-time",
                },
                {
                    "name": "minutes_per_occurrence",
                    "label": "Minutes per occurrence",
                    "type": "text",
                    "required": False,
                    "max_chars": 30,
                    "placeholder": "60",
                    "depends_on": {"field": "mode", "value": "enjoyment"},
                },
                {
                    "name": "target_value_per_hour",
                    "label": "Target value per hour (optional)",
                    "type": "text",
                    "required": False,
                    "max_chars": 30,
                    "placeholder": "25",
                    "depends_on": {"field": "mode", "value": "enjoyment"},
                },
                {
                    "name": "timeframe_months",
                    "label": "Timeframe (months, optional)",
                    "type": "text",
                    "required": False,
                    "max_chars": 30,
                    "placeholder": "12",
                },
                {
                    "name": "minutes_saved_per_use",
                    "label": "Minutes saved per use",
                    "type": "text",
                    "required": False,
                    "max_chars": 30,
                    "placeholder": "10",
                    "depends_on": {"field": "mode", "value": "time_saved"},
                },
                {
                    "name": "hourly_value",
                    "label": "Your hourly value",
                    "type": "text",
                    "required": False,
                    "max_chars": 30,
                    "placeholder": "30",
                    "depends_on": {"field": "mode", "value": "time_saved"},
                },
                {
                    "name": "expected_uses_per_month",
                    "label": "Expected uses per month (optional)",
                    "type": "text",
                    "required": False,
                    "max_chars": 30,
                    "placeholder": "12",
                    "depends_on": {"field": "mode", "value": "time_saved"},
                },
                {
                    "name": "compare_enabled",
                    "label": "Compare against another option?",
                    "type": "select",
                    "required": False,
                    "max_chars": 5,
                    "placeholder": "",
                    "options": ["No", "Yes"],
                    "default": "No",
                },
                {
                    "name": "option_b_name",
                    "label": "Option B name",
                    "type": "text",
                    "required": False,
                    "max_chars": 80,
                    "placeholder": "Option B",
                    "depends_on": {"field": "compare_enabled", "value": "Yes"},
                },
                {
                    "name": "option_b_cost",
                    "label": "Option B cost",
                    "type": "text",
                    "required": False,
                    "max_chars": 30,
                    "placeholder": "200",
                    "depends_on": {"field": "compare_enabled", "value": "Yes"},
                },
                {
                    "name": "option_b_minutes",
                    "label": "Option B minutes per occurrence/use",
                    "type": "text",
                    "required": False,
                    "max_chars": 30,
                    "placeholder": "45",
                    "depends_on": {"field": "compare_enabled", "value": "Yes"},
                },
                {
                    "name": "option_b_frequency",
                    "label": "Option B frequency",
                    "type": "select",
                    "required": False,
                    "max_chars": 20,
                    "placeholder": "",
                    "options": ["One-time", "Daily", "Weekly", "Biweekly", "Monthly", "Yearly"],
                    "default": "One-time",
                    "depends_on": {"field": "compare_enabled", "value": "Yes"},
                },
                {
                    "name": "option_b_hourly_value",
                    "label": "Option B hourly value (optional)",
                    "type": "text",
                    "required": False,
                    "max_chars": 30,
                    "placeholder": "",
                    "depends_on": {"field": "compare_enabled", "value": "Yes"},
                },
                {
                    "name": "nudge_enabled",
                    "label": "Enable buy now vs wait nudge?",
                    "type": "select",
                    "required": False,
                    "max_chars": 5,
                    "placeholder": "",
                    "options": ["No", "Yes"],
                    "default": "No",
                },
                {
                    "name": "return_window_days",
                    "label": "Return window days",
                    "type": "text",
                    "required": False,
                    "max_chars": 30,
                    "placeholder": "30",
                    "depends_on": {"field": "nudge_enabled", "value": "Yes"},
                },
                {
                    "name": "quit_chance_percent",
                    "label": "Quit chance percent",
                    "type": "text",
                    "required": False,
                    "max_chars": 30,
                    "placeholder": "10",
                    "depends_on": {"field": "nudge_enabled", "value": "Yes"},
                },
                    {
                    "name": "follow_through_percent",
                    "label": "Follow-through percent",
                    "type": "text",
                    "required": False,
                    "max_chars": 30,
                    "placeholder": "80",
                    "depends_on": {"field": "nudge_enabled", "value": "Yes"},
                },
                {
                    "name": "notes",
                    "label": "Assumptions (optional)",
                    "type": "textarea",
                    "required": False,
                    "max_chars": 600,
                    "placeholder": "Any assumptions",
                },
            ],
        },
    ]


def get_enabled_tools() -> List[ToolEntry]:
    return [tool for tool in get_tools_registry() if tool.get("is_enabled")]


def get_tool_by_slug(slug: str) -> Optional[ToolEntry]:
    for tool in get_tools_registry():
        if tool.get("slug") == slug:
            return tool
    return None
